add ct_test and ci change

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -319,6 +319,34 @@ jobs:
         run: python3 ./src/scripts/ci_build.py --cc='${{ matrix.compiler }}' --make-tool='${{ matrix.make_tool }}' --test-results-dir=junit_results ${{ matrix.target }}
   
 
+  dudect:
+    name: "dudect-CT"
+    runs-on: ubuntu-latest
+    needs: [linux]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install prerequisites
+        run: sudo apt-get update && sudo apt-get install -y util-linux coreutils
+      - name: DudeCT clone
+        run: git clone https://github.com/oreparaz/dudect.git
+      - name: DudeCT build
+        run: make -C dudect
+      - name: compile ct_test.cpp
+        env:
+          BOTAN_INC: ${{ github.workspace }}/src/include
+          BOTAN_LIB: ${{ github.workspace }}/build/lib
+          DUDECT_INC: ${{ github.workspace }}/dudect/src
+        run: |
+          g++ -std=c++20 -O2 \
+            -I"${BOTAN_INC}" \
+            -I"${DUDECT_INC}" \
+            ${{ github.workspace }}/tests/dudect/ct_test.cpp -o ct_test_bin \
+            -L"${BOTAN_LIB}" -lbotan-3 -pthread -lm
+      - name: ct_test execute
+        run: taskset -c 2 timeout 300s ./ct_test
+      - name: Print result
+        run: |
+          if [ $? -eq 0 ]; then echo "PASSED"; else echo "FAILED"; exit 1; fi
   #dudect:
   #  name: "Dudect Timing Test"
   #  runs-on: ubuntu-24.04
